from tkinter import *
root=Tk()
root.geometry("300x400+200+100")
#root.title("my first app")
#g=Label(text="my label",bg="red",fg="gray",font=("courier",25,"bold"))
#g.pack()
#f=Label(text="my label",bg="red",relief="groove",borderwidth=15,fg="gray",font=("courier",25,"bold"))
#f.pack()
#f=Label(text="my label",bg="red",relief="raised",borderwidth=15,fg="gray",font=("courier",25,"bold"))
#f.pack()
#logo=PhotoImage(file="yazan.gif")
#label=Label(root,image=logo)
#label.pack()
"""
lb=Button(root,text="my text",bg="red")
lb.pack(padx=20,pady=30)
"""
"""
lb=Button(root,text="my text",bg="blue")
lb.pack(side=BOTTOM)
lb=Button(root,text="my text",bg="yellow")
lb.pack(side=LEFT)
lb=Button(root,text="my text",bg="green")
lb.pack(side=RIGHT)
lb=Button(root,text="my text",bg="pink")
lb.pack(side=BOTTOM,anchor=SE)
lb=Button(root,text="my text",bg="pink")
lb.pack(side=BOTTOM,anchor=SW)
lb=Button(root,text="my text",bg="pink")
lb.pack(anchor=NE)
lb=Button(root,text="my text",bg="pink")
lb.pack(anchor=NW)
"""
"""
lb=Button(root,text="my text",bg="green")
lb.place(x=50,y=30,width=200,height=100)

lb=Button(root,text="my text",bg="green")
lb.place(x=50,y=20,width=200,height=100)
#g.configure(text="changed",bg="blue")
"""
user=Label(root,text="Username: ")
user.grid(row=0,padx=20,pady=20)
user=Label(root,text="password: ")
user.grid(row=1)
user=Entry(root)
user.grid(row=0,column=1)
user=Entry(root)
user.grid(row=1,column=1)
lb=Button(root,text="login",bg="red")
lb.grid(row=2,column=1,pady=20)
root.mainloop()